version: '2.1'
services:

    webapp:
        image: node:9.9
        networks:
            - development
        ports:
            - ${APP_PORT:-3000}:3000
            - ${SSR_PORT:-8080}:8080
        environment:
            NODE_ENV: development
            LOG_LEVEL: ${LOG_LEVEL-info}
            SSR_DISABLE_JS: ${SSR_DISABLE_JS-no}
            SSR_USE_DYNAMIC_JS: ${SSR_USE_DYNAMIC_JS-no}
        volumes:
            - ./services/webapp:/usr/src/app
        working_dir: /usr/src/app
        entrypoint: [ "yarn", "start:dev" ]

networks:
    development:
