version: '3.4'
services:

    frontend:
        image: node:9.7
        networks:
            - default
        ports:
            - ${APP_PORT:-3000}:3000
            - ${SSR_PORT:-8080}:8080
        volumes:
            - ./services/frontend:/usr/src/app
        environment:
            NODE_ENV: development
            LOG_LEVEL: ${LOG_LEVEL-info}
        working_dir: /usr/src/app
        entrypoint: [ "yarn", "start:dev" ]

networks:
    default:
