version: '2.1'
services:

    webapp:
        build: ./services/webapp
        networks:
            - production
        environment:
            NODE_ENV: production
            LOG_LEVEL: ${LOG_LEVEL-verbose}

    proxy:
        build: ./services/nginx-proxy
        networks:
            - production
        ports:
            - ${PROXY_PORT:-80}:80
        environment:
            NGINX_UPSTREAM_SERVER: webapp
            NGINX_UPSTREAM_PORT: 8080
        volumes:
            - ./services/webapp/build:/usr/share/nginx/html



    # proxy:
    #     image: nginx:1.13
    #     depends_on:
    #         - webapp
    #     networks:
    #         - production
    #     ports:
    #         - ${PROXY_PORT:-80}:80
    #     volumes:
    #         - ./services/nginx-proxy/nginx.static.conf:/etc/nginx/nginx.conf
    #         - ./services/nginx-proxy/h5bp:/etc/nginx/h5bp
    #         - ./services/nginx-proxy/h5bp-full:/etc/nginx/h5bp-full
    #         - ./services/nginx-proxy/.htpasswd:/etc/nginx/.htpasswd
    #         - ./services/webapp/build:/usr/share/nginx/html

networks:
    production:
