version: '2.1'
services:

    webapp:
        build: ./services/webapp
        networks:
            - production
        environment:
            NODE_ENV: production
            LOG_LEVEL: ${LOG_LEVEL-verbose}

    proxy:
        build: ./services/nginx-proxy
        networks:
            - production
        ports:
            - ${PROXY_PORT:-80}:80
        environment:
            NGINX_UPSTREAM_SERVER: webapp
            NGINX_UPSTREAM_PORT: 8080
        volumes_from:
            - webapp

networks:
    production:
